insert into poll(title, question, answer1, answer2, answer3, votes1, votes2, votes3)values
('Describe in ONE word', 
'In one word how would you describe your past week/month?',
'Heavy',
'Fun',
'Intense',
'20',
'5',
'15'
),
('Any favourites?', 
'What is your favourite ice cream?',
'Mint',
'Chocolate',
'Strawberry',
'3',
'25',
'12'),
('Random Answer!',
'Have you ever answered a poll question with a random answer?',
'Yes',
'No',
'Ice Cream',
'10',
'12',
'18'),
('Would you rather...',
'Would you rather be able to',
'See Future',
'Read Minds',
'Teleport Anywhere',
'15',
'8',
'17'),
('Strangest things',
'What is the strangest thing you did while attending an online class?',
'Brushed Teeth',
'Watched Netflix',
'Others but my lips are sealed ;)',
'8',
'22',
'10');
